// Date: 12/15/2013 12:21:50 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.beards.client.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.nbt.NBTTagCompound;

public class ModelDwarfBeard extends ModelBeardBase
{
	//fields
	ModelRenderer stage13c, stage3b, stage12d, stage4b, stage3a, stage9b, stage2a, stage5b, stage4a, stage2c, stage7b, stage6b, stage9a, stage6a, stage7d;

	ModelRenderer stage2b, stage7c, stage7a, stage5a, stage5c, stage10, stage13d, stage12c, stage13e, stage11c, stage14d, stage14e, stage15e, stage11a;

	ModelRenderer stage12b, stage13a, stage14a, stage15a, stage11b, shape13b, stage14b, stage15b, stage15d, stage15c, stage14c, stage1, stage5d;

	ModelRenderer stage11d, stage11e, stage12e, stage12a;

	public ModelDwarfBeard()
	{
		textureWidth = 32;
		textureHeight = 32;

		stage13c = new ModelRenderer(this, 12, 27);
		stage13c.addBox(-0.5F, 5F, -2.3F, 1, 2, 2);
		stage13c.setRotationPoint(0F, 0F, 0F);
		stage13c.setTextureSize(32, 32);
		stage13c.mirror = true;
		setRotation(stage13c, -0.5235988F, 0F, 0F);
		stage3b = new ModelRenderer(this, 0, 2);
		stage3b.addBox(-1.35F, -3.1F, -4.2F, 2, 1, 1);
		stage3b.setRotationPoint(0F, 0F, 0F);
		stage3b.setTextureSize(32, 32);
		stage3b.mirror = true;
		setRotation(stage3b, 0F, 0F, -0.5235988F);
		stage12d = new ModelRenderer(this, 18, 3);
		stage12d.addBox(1.25F, 2.9F, -4.4F, 1, 3, 1);
		stage12d.setRotationPoint(0F, 0F, 0F);
		stage12d.setTextureSize(32, 32);
		stage12d.mirror = true;
		setRotation(stage12d, -0.3839724F, 0F, 0F);
		stage4b = new ModelRenderer(this, 6, 10);
		stage4b.addBox(1.7F, -2F, -4.2F, 1, 2, 1);
		stage4b.setRotationPoint(0F, 0F, 0F);
		stage4b.setTextureSize(32, 32);
		stage4b.mirror = true;
		setRotation(stage4b, 0F, 0F, 0F);
		stage3a = new ModelRenderer(this, 0, 2);
		stage3a.addBox(-0.6F, -3.1F, -4.2F, 2, 1, 1);
		stage3a.setRotationPoint(0F, 0F, 0F);
		stage3a.setTextureSize(32, 32);
		stage3a.mirror = true;
		setRotation(stage3a, 0F, 0F, 0.5235988F);
		stage9b = new ModelRenderer(this, 18, 3);
		stage9b.addBox(2.4F, -2.99F, -4.15F, 1, 2, 1);
		stage9b.setRotationPoint(0F, 1F, 0F);
		stage9b.setTextureSize(32, 32);
		stage9b.mirror = true;
		setRotation(stage9b, 0F, 0F, 0F);
		stage2a = new ModelRenderer(this, 6, 2);
		stage2a.addBox(-1F, -1F, -4.2F, 2, 1, 1);
		stage2a.setRotationPoint(0F, 0.3F, 0F);
		stage2a.setTextureSize(32, 32);
		stage2a.mirror = true;
		setRotation(stage2a, 0F, 0F, 0F);
		stage5b = new ModelRenderer(this, 0, 10);
		stage5b.addBox(-2.8F, -1F, -4.2F, 2, 1, 1);
		stage5b.setRotationPoint(0F, 0.3F, 0F);
		stage5b.setTextureSize(32, 32);
		stage5b.mirror = true;
		setRotation(stage5b, 0F, 0F, 0F);
		stage4a = new ModelRenderer(this, 6, 10);
		stage4a.addBox(-2.8F, -2F, -4.2F, 1, 2, 1);
		stage4a.setRotationPoint(0F, 0F, 0F);
		stage4a.setTextureSize(32, 32);
		stage4a.mirror = true;
		setRotation(stage4a, 0F, 0F, 0F);
		stage2c = new ModelRenderer(this, 14, 4);
		stage2c.addBox(3.1F, -2.99F, -3.99F, 1, 1, 1);
		stage2c.setRotationPoint(0F, 0F, 0F);
		stage2c.setTextureSize(32, 32);
		stage2c.mirror = true;
		setRotation(stage2c, 0F, 0F, 0F);
		stage7b = new ModelRenderer(this, 12, 1);
		stage7b.addBox(-4.1F, -2F, -3.1F, 1, 1, 2);
		stage7b.setRotationPoint(0F, 0F, 0F);
		stage7b.setTextureSize(32, 32);
		stage7b.mirror = true;
		setRotation(stage7b, 0F, 0F, 0F);
		stage6b = new ModelRenderer(this, 14, 4);
		stage6b.addBox(3.1F, -2.99F, -4.1F, 1, 1, 1);
		stage6b.setRotationPoint(0F, 1F, 0F);
		stage6b.setTextureSize(32, 32);
		stage6b.mirror = true;
		setRotation(stage6b, 0F, 0F, 0F);
		stage9a = new ModelRenderer(this, 6, 10);
		stage9a.addBox(-3.3F, -2.99F, -4.15F, 1, 2, 1);
		stage9a.setRotationPoint(0F, 1F, 0F);
		stage9a.setTextureSize(32, 32);
		stage9a.mirror = true;
		setRotation(stage9a, 0F, 0F, 0F);
		stage6a = new ModelRenderer(this, 14, 4);
		stage6a.addBox(-4.1F, -2.99F, -4.1F, 1, 1, 1);
		stage6a.setRotationPoint(0F, 1F, 0F);
		stage6a.setTextureSize(32, 32);
		stage6a.mirror = true;
		setRotation(stage6a, 0F, 0F, 0F);
		stage7d = new ModelRenderer(this, 14, 4);
		stage7d.addBox(-4.1F, -1.99F, -4.1F, 1, 1, 1);
		stage7d.setRotationPoint(0F, 1F, 0F);
		stage7d.setTextureSize(32, 32);
		stage7d.mirror = true;
		setRotation(stage7d, 0F, 0F, 0F);
		stage2b = new ModelRenderer(this, 14, 4);
		stage2b.addBox(-4.1F, -2.99F, -3.99F, 1, 1, 1);
		stage2b.setRotationPoint(0F, 0F, 0F);
		stage2b.setTextureSize(32, 32);
		stage2b.mirror = true;
		setRotation(stage2b, 0F, 0F, 0F);
		stage7c = new ModelRenderer(this, 14, 4);
		stage7c.addBox(3.1F, -1.99F, -4.1F, 1, 1, 1);
		stage7c.setRotationPoint(0F, 1F, 0F);
		stage7c.setTextureSize(32, 32);
		stage7c.mirror = true;
		setRotation(stage7c, 0F, 0F, 0F);
		stage7a = new ModelRenderer(this, 12, 1);
		stage7a.addBox(3.1F, -1.99F, -3.1F, 1, 1, 2);
		stage7a.setRotationPoint(0F, 0F, 0F);
		stage7a.setTextureSize(32, 32);
		stage7a.mirror = true;
		setRotation(stage7a, 0F, 0F, 0F);
		stage5a = new ModelRenderer(this, 6, 0);
		stage5a.addBox(-2.8F, -1F, -4.2F, 2, 1, 1);
		stage5a.setRotationPoint(3.5F, 0.3F, 0F);
		stage5a.setTextureSize(32, 32);
		stage5a.mirror = true;
		setRotation(stage5a, 0F, 0F, 0F);
		stage5c = new ModelRenderer(this, 0, 4);
		stage5c.addBox(-3F, -0.9F, -3.2F, 6, 1, 1);
		stage5c.setRotationPoint(0F, 0F, 0F);
		stage5c.setTextureSize(32, 32);
		stage5c.mirror = true;
		setRotation(stage5c, 0F, 0F, 0F);
		stage10 = new ModelRenderer(this, 0, 6);
		stage10.addBox(-3.5F, 0.1F, -4.2F, 7, 1, 3);
		stage10.setRotationPoint(0F, 0F, 0F);
		stage10.setTextureSize(32, 32);
		stage10.mirror = true;
		setRotation(stage10, -0.0523599F, 0F, 0F);
		stage13d = new ModelRenderer(this, 0, 18);
		stage13d.addBox(0.5F, 5F, -2.9F, 2, 2, 3);
		stage13d.setRotationPoint(0F, 0F, 0F);
		stage13d.setTextureSize(32, 32);
		stage13d.mirror = true;
		setRotation(stage13d, -0.5235988F, 0F, 0F);
		stage12c = new ModelRenderer(this, 0, 13);
		stage12c.addBox(2F, 3F, -3.1F, 1, 2, 3);
		stage12c.setRotationPoint(0F, 0F, 0F);
		stage12c.setTextureSize(32, 32);
		stage12c.mirror = true;
		setRotation(stage12c, -0.5235988F, 0F, 0F);
		stage13e = new ModelRenderer(this, 0, 18);
		stage13e.addBox(2.5F, 5F, -3.1F, 1, 2, 3);
		stage13e.setRotationPoint(0F, 0F, 0F);
		stage13e.setTextureSize(32, 32);
		stage13e.mirror = true;
		setRotation(stage13e, -0.5235988F, 0F, 0F);
		stage11c = new ModelRenderer(this, 0, 13);
		stage11c.addBox(2F, 1F, -4.1F, 1, 2, 3);
		stage11c.setRotationPoint(0F, 0F, 0F);
		stage11c.setTextureSize(32, 32);
		stage11c.mirror = true;
		setRotation(stage11c, -0.1745329F, 0F, 0F);
		stage14d = new ModelRenderer(this, 0, 23);
		stage14d.addBox(1F, 7F, -1.7F, 2, 3, 3);
		stage14d.setRotationPoint(0F, 0F, 0F);
		stage14d.setTextureSize(32, 32);
		stage14d.mirror = true;
		setRotation(stage14d, -0.6981317F, 0F, 0F);
		stage14e = new ModelRenderer(this, 0, 23);
		stage14e.addBox(3F, 7F, -1.9F, 1, 3, 3);
		stage14e.setRotationPoint(0F, 0F, 0F);
		stage14e.setTextureSize(32, 32);
		stage14e.mirror = true;
		setRotation(stage14e, -0.6981317F, 0F, 0F);
		stage15e = new ModelRenderer(this, 12, 28);
		stage15e.addBox(3.5F, 10F, -1.4F, 1, 1, 2);
		stage15e.setRotationPoint(0F, 0F, 0F);
		stage15e.setTextureSize(32, 32);
		stage15e.mirror = true;
		setRotation(stage15e, -0.6981317F, 0F, 0F);
		stage11a = new ModelRenderer(this, 0, 13);
		stage11a.addBox(-3F, 1F, -4.1F, 1, 2, 3);
		stage11a.setRotationPoint(0F, 0F, 0F);
		stage11a.setTextureSize(32, 32);
		stage11a.mirror = true;
		setRotation(stage11a, -0.1745329F, 0F, 0F);
		stage12b = new ModelRenderer(this, 0, 13);
		stage12b.addBox(-2F, 3F, -2.9F, 4, 2, 3);
		stage12b.setRotationPoint(0F, 0F, 0F);
		stage12b.setTextureSize(32, 32);
		stage12b.mirror = true;
		setRotation(stage12b, -0.5235988F, 0F, 0F);
		stage13a = new ModelRenderer(this, 0, 18);
		stage13a.addBox(-3.5F, 5F, -3.1F, 1, 2, 3);
		stage13a.setRotationPoint(0F, 0F, 0F);
		stage13a.setTextureSize(32, 32);
		stage13a.mirror = true;
		setRotation(stage13a, -0.5235988F, 0F, 0F);
		stage14a = new ModelRenderer(this, 0, 23);
		stage14a.addBox(-4F, 7F, -1.9F, 1, 3, 3);
		stage14a.setRotationPoint(0F, 0F, 0F);
		stage14a.setTextureSize(32, 32);
		stage14a.mirror = true;
		setRotation(stage14a, -0.6981317F, 0F, 0F);
		stage15a = new ModelRenderer(this, 12, 28);
		stage15a.addBox(-4.5F, 10F, -1.4F, 1, 1, 2);
		stage15a.setRotationPoint(0F, 0F, 0F);
		stage15a.setTextureSize(32, 32);
		stage15a.mirror = true;
		setRotation(stage15a, -0.6981317F, 0F, 0F);
		stage11b = new ModelRenderer(this, 0, 13);
		stage11b.addBox(-2F, 1F, -3.9F, 4, 2, 3);
		stage11b.setRotationPoint(0F, 0F, 0F);
		stage11b.setTextureSize(32, 32);
		stage11b.mirror = true;
		setRotation(stage11b, -0.1745329F, 0F, 0F);
		shape13b = new ModelRenderer(this, 0, 18);
		shape13b.addBox(-2.5F, 5F, -2.9F, 2, 2, 3);
		shape13b.setRotationPoint(0F, 0F, 0F);
		shape13b.setTextureSize(32, 32);
		shape13b.mirror = true;
		setRotation(shape13b, -0.5235988F, 0F, 0F);
		stage14b = new ModelRenderer(this, 0, 23);
		stage14b.addBox(-3F, 7F, -1.7F, 2, 3, 3);
		stage14b.setRotationPoint(0F, 0F, 0F);
		stage14b.setTextureSize(32, 32);
		stage14b.mirror = true;
		setRotation(stage14b, -0.6981317F, 0F, 0F);
		stage15b = new ModelRenderer(this, 12, 28);
		stage15b.addBox(-3.5F, 10F, -1.3F, 2, 2, 2);
		stage15b.setRotationPoint(0F, 0F, 0F);
		stage15b.setTextureSize(32, 32);
		stage15b.mirror = true;
		setRotation(stage15b, -0.6981317F, 0F, 0F);
		stage15d = new ModelRenderer(this, 12, 28);
		stage15d.addBox(1.5F, 10F, -1.3F, 2, 2, 2);
		stage15d.setRotationPoint(0F, 0F, 0F);
		stage15d.setTextureSize(32, 32);
		stage15d.mirror = true;
		setRotation(stage15d, -0.6981317F, 0F, 0F);
		stage15c = new ModelRenderer(this, 12, 27);
		stage15c.addBox(-1.5F, 10F, -1.3F, 3, 3, 2);
		stage15c.setRotationPoint(0F, 0F, 0F);
		stage15c.setTextureSize(32, 32);
		stage15c.mirror = true;
		setRotation(stage15c, -0.6981317F, 0F, 0F);
		stage14c = new ModelRenderer(this, 12, 27);
		stage14c.addBox(-1F, 7F, -1.3F, 2, 3, 2);
		stage14c.setRotationPoint(0F, 0F, 0F);
		stage14c.setTextureSize(32, 32);
		stage14c.mirror = true;
		setRotation(stage14c, -0.6981317F, 0F, 0F);
		stage1 = new ModelRenderer(this, 0, 0);
		stage1.addBox(-1F, -3F, -4.2F, 2, 1, 1);
		stage1.setRotationPoint(0F, 0F, 0F);
		stage1.setTextureSize(32, 32);
		stage1.mirror = true;
		setRotation(stage1, 0F, 0F, 0F);
		stage5d = new ModelRenderer(this, 0, 0);
		stage5d.addBox(-1.5F, -0.5F, -4.8F, 3, 1, 1);
		stage5d.setRotationPoint(0F, 0F, 0F);
		stage5d.setTextureSize(32, 32);
		stage5d.mirror = true;
		setRotation(stage5d, 0F, 0F, 0F);
		stage11d = new ModelRenderer(this, 18, 3);
		stage11d.addBox(1F, 1.3F, -4.4F, 1, 2, 1);
		stage11d.setRotationPoint(0F, 0F, 0F);
		stage11d.setTextureSize(32, 32);
		stage11d.mirror = true;
		setRotation(stage11d, -0.3490659F, 0F, -0.1745329F);
		stage11e = new ModelRenderer(this, 18, 3);
		stage11e.addBox(-2F, 1.3F, -4.4F, 1, 2, 1);
		stage11e.setRotationPoint(0F, 0F, 0F);
		stage11e.setTextureSize(32, 32);
		stage11e.mirror = true;
		setRotation(stage11e, -0.3490659F, 0F, 0.1745329F);
		stage12e = new ModelRenderer(this, 18, 3);
		stage12e.addBox(-2.25F, 2.9F, -4.4F, 1, 3, 1);
		stage12e.setRotationPoint(0F, 0F, 0F);
		stage12e.setTextureSize(32, 32);
		stage12e.mirror = true;
		setRotation(stage12e, -0.3839724F, 0F, 0F);
		stage12a = new ModelRenderer(this, 0, 13);
		stage12a.addBox(-3F, 3F, -3.1F, 1, 2, 3);
		stage12a.setRotationPoint(0F, 0F, 0F);
		stage12a.setTextureSize(32, 32);
		stage12a.mirror = true;
		setRotation(stage12a, -0.5235988F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, int beardStage, int growStage)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		if (beardStage >= 1)
			stage1.render(f5);
		if (beardStage >= 2)
		{
			stage2a.render(f5);
			stage2b.render(f5);
			stage2c.render(f5);
		}
		if (beardStage >= 3)
		{
			stage3a.render(f5);
			stage3b.render(f5);
		}
		if (beardStage >= 4)
		{
			stage4a.render(f5);
			stage4b.render(f5);
		}
		if (beardStage >= 5)
		{
			stage5a.render(f5);
			stage5b.render(f5);
			stage5c.render(f5);
			stage5d.render(f5);
		}
		if (beardStage >= 6)
		{
			stage6a.render(f5);
			stage6b.render(f5);
		}
		if (beardStage >= 7)
		{
			stage7a.render(f5);
			stage7b.render(f5);
			stage7d.render(f5);
			stage7c.render(f5);
		}
		if (beardStage >= 8)
		{
			stage9a.render(f5);
			stage9b.render(f5);
		}
		NBTTagCompound tag = entity.getEntityData();
		Minecraft mc = Minecraft.getMinecraft();
		if (mc.currentScreen == null || (mc.currentScreen != null && !mc.currentScreen.doesGuiPauseGame()))
		{
			if (f1 > 0 || f1 < -0.8F)
				GL11.glRotatef((float) -Math.cos((float) f1) * 8 * (float) f1 * 3, 5, 0, 0);
			GL11.glTranslatef(0, -0.05f, 0);
			if (tag != null)
			{
				GL11.glRotatef((float) Math.cos(f) * 5, 0.5f, 1.0f, 0.0f);
				GL11.glRotatef((float) Math.sin(f) * 5, 0.0f, 1.0f, 0.5f);
			}
			if (entity != null && !(entity.rotationPitch < -10))
				GL11.glRotatef(-entity.rotationPitch, (entity.rotationPitch * 180 / (float) Math.PI), 0, 0);
		}
		if (beardStage >= 10)
			stage10.render(f5);
		if (beardStage >= 11)
		{
			stage11c.render(f5);
			stage11a.render(f5);
			stage11b.render(f5);
			stage11d.render(f5);
			stage11e.render(f5);
		}
		if (beardStage >= 12)
		{
			stage12a.render(f5);
			stage12b.render(f5);
			stage12c.render(f5);
			stage12d.render(f5);
			stage12e.render(f5);
		}
		if (beardStage >= 13)
		{
			stage13a.render(f5);
			shape13b.render(f5);
			stage13c.render(f5);
			stage13d.render(f5);
			stage13e.render(f5);
		}
		if (beardStage >= 14)
		{
			stage14a.render(f5);
			stage14b.render(f5);
			stage14d.render(f5);
			stage14e.render(f5);
			stage14c.render(f5);
		}
		if (beardStage >= 15)
		{
			stage15b.render(f5);
			stage15a.render(f5);
			stage15e.render(f5);
			stage15d.render(f5);
			stage15c.render(f5);
		}
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
}
